export const ruCategories = {
  'ecommerce-marketplace-automation': 'E-Commerce и маркетплейсы', 'workforce-hr-automation': 'Персонал и HR',
  'ai-business-solutions': 'AI-решения для бизнеса', 'supply-chain-warehouse': 'Логистика и склад',
  'industrial-ai-manufacturing': 'Промышленный AI', 'hospitality-hotel-software': 'Гостеприимство',
  'automotive-software': 'Автомобильные решения', 'finance-accounting-automation': 'Финансы и учёт',
  'custom-software-business-automation': 'Заказная разработка',
};

export const copy = {
  de: { edit: 'PROJEKT BEARBEITEN', new: 'NEUES PROJEKT', createTitle: 'Portfolio-Projekt anlegen', cancel: 'Abbrechen', name: 'Name', category: 'Kategorie', time: 'Entwicklungszeit', stack: 'Stack', description: 'Beschreibung', descriptionEn: 'Beschreibung (Englisch, für /en)', stackEn: 'Tags (Englisch)', screenshot: 'Screenshot', addImages: '(neue Bilder werden ergänzt)', public: 'Auf der öffentlichen Portfolio-Seite anzeigen', save: 'Projekt speichern', saveChanges: 'Änderungen speichern', published: 'Wird veröffentlicht', draft: 'Bleibt ein Entwurf', preview: 'LIVE-VORSCHAU', noScreenshot: 'Screenshot', projectName: 'Projektname', previewDescription: 'Die Beschreibung des Projekts erscheint hier.', projects: 'Portfolio verwalten', subtitle: 'Projekte bearbeiten, veröffentlichen und in der finalen Kartenansicht prüfen.', newProject: 'Neues Projekt', all: 'Alle Projekte', live: 'Veröffentlicht', drafts: 'Entwürfe', allProjects: 'Alle Projekte', entries: 'Einträge', publishedStatus: 'Veröffentlicht', draftStatus: 'Entwurf', editButton: 'Bearbeiten', deleteButton: 'Löschen', confirmDelete: 'endgültig löschen?', created: 'Projekt angelegt.', updated: 'Projekt aktualisiert.', deleted: 'Projekt gelöscht.', saveError: 'Projekt konnte nicht gespeichert werden.', deleteError: 'Projekt konnte nicht gelöscht werden.', loginTitle: 'Admin', loginHint: 'Mit einem Django-Administrator anmelden.', username: 'Benutzername', password: 'Passwort', login: 'Anmelden', loginError: 'Anmeldedaten ungültig.', welcome: 'Willkommen zurück.', logout: 'Abmelden', tabProjects: 'Portfolio', tabLeads: 'Anfragen', leadsTitle: 'Kontaktanfragen', noLeads: 'Noch keine Anfragen.', source: 'Quelle' },
  ru: { edit: 'РЕДАКТИРОВАНИЕ ПРОЕКТА', new: 'НОВЫЙ ПРОЕКТ', createTitle: 'Создать проект для портфолио', cancel: 'Отмена', name: 'Название', category: 'Категория', time: 'Срок разработки', stack: 'Стек', description: 'Описание', descriptionEn: 'Описание (английский, для /en)', stackEn: 'Теги (английский)', screenshot: 'Скриншоты', addImages: '(новые изображения будут добавлены)', public: 'Показывать на публичной странице портфолио', save: 'Сохранить проект', saveChanges: 'Сохранить изменения', published: 'Будет опубликован', draft: 'Останется черновиком', preview: 'ПРЕДПРОСМОТР', noScreenshot: 'Скриншот', projectName: 'Название проекта', previewDescription: 'Здесь появится описание проекта.', projects: 'Управление портфолио', subtitle: 'Редактируйте, публикуйте проекты и проверяйте вид итоговой карточки.', newProject: 'Новый проект', all: 'Всего проектов', live: 'Опубликовано', drafts: 'Черновики', allProjects: 'Все проекты', entries: 'записей', publishedStatus: 'Опубликован', draftStatus: 'Черновик', editButton: 'Редактировать', deleteButton: 'Удалить', confirmDelete: 'удалить безвозвратно?', created: 'Проект создан.', updated: 'Проект обновлён.', deleted: 'Проект удалён.', saveError: 'Не удалось сохранить проект.', deleteError: 'Не удалось удалить проект.', loginTitle: 'Админка', loginHint: 'Войдите с учётной записью администратора Django.', username: 'Имя пользователя', password: 'Пароль', login: 'Войти', loginError: 'Неверные данные для входа.', welcome: 'Добро пожаловать.', logout: 'Выйти', tabProjects: 'Портфолио', tabLeads: 'Заявки', leadsTitle: 'Заявки с сайта', noLeads: 'Заявок пока нет.', source: 'Источник' },
};

export const categoryName = (project, lang) => (lang === 'ru' ? ruCategories[project.category] || project.category_label : project.category_label);
