# Generated by Django 6.1.2 on 2026-10-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_update_hubnity_and_lisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
