import { SiteFooter, SiteHeader } from '@/components/site-chrome';

const content = {
  unternehmen: { eyebrow: 'Über uns', title: 'Software entsteht im Dialog.', intro: 'AutomatonSoft entwickelt digitale Lösungen für Unternehmen, die ihre Prozesse wirksam verbessern wollen.', sections: [['Was uns auszeichnet', 'Wir verbinden fachliches Verständnis, klare Kommunikation und solide technische Umsetzung.', ['Direkte Ansprechpartner', 'Individuelle Lösungen statt Standardprozesse', 'Von der Idee bis zum Betrieb']], ['Unser Vorgehen', 'Wir starten mit Ihren Anforderungen, entwickeln transparent in Etappen und verbessern kontinuierlich.', ['Analyse & Konzept', 'Entwicklung & Qualitätssicherung', 'Betrieb & Weiterentwicklung']]] },
  dienstleistungen: { eyebrow: 'Leistungen', title: 'Technologie, die zu Ihrem Unternehmen passt.', intro: 'Von der Beratung bis zum Betrieb: Wir entwickeln digitale Produkte, Schnittstellen und automatisierte Prozesse.', sections: [['Softwareentwicklung', 'Maßgeschneiderte Web-, Desktop- und Backend-Anwendungen für komplexe Geschäftsprozesse.', ['Individuelle Business-Software', 'Schnittstellen & Integrationen', 'Daten- und Prozessautomatisierung']], ['Digitale Produkte', 'Wir gestalten und entwickeln Anwendungen, die für Mitarbeitende und Kunden einfach funktionieren.', ['Web-Entwicklung', 'Mobile Apps', 'UI/UX Gestaltung']]] },
  branchen: { eyebrow: 'Branchen', title: 'Lösungen für echte Arbeitsabläufe.', intro: 'Unsere Erfahrung reicht von E-Commerce und Logistik bis zu Industrie, Hospitality und Automotive.', sections: [['E-Commerce & Handel', 'Produktdaten, Marktplätze, Bestellungen und Backoffice-Prozesse zuverlässig verbinden.', ['Marketplace Automation', 'Produktdatenmanagement', 'Order Management']], ['Industrie & Dienstleistung', 'Digitale Systeme für Planung, Organisation und kontinuierliche Verbesserung.', ['Workforce Management', 'Industrial AI', 'Finance & Accounting']]] },
  'entwickler-engagieren': { eyebrow: 'Teams & Spezialisten', title: 'Entwicklungs-Know-how, wenn Sie es brauchen.', intro: 'Ergänzen Sie Ihr Team mit erfahrenen Spezialistinnen und Spezialisten für konkrete Projekte oder langfristige Vorhaben.', sections: [['Flexibel skalieren', 'Wir arbeiten als dediziertes Team, ergänzen vorhandene Teams oder übernehmen klar abgegrenzte Projekte.', ['Full-Stack Entwicklung', 'Web & Mobile', 'DevOps, QA und UI/UX']], ['Klar zusammenarbeiten', 'Sie erhalten transparente Kommunikation, nachvollziehbare Ergebnisse und einen festen technischen Ansprechpartner.', ['Direkte Abstimmung', 'Planbare Etappen', 'Langfristige Zusammenarbeit']]] },
  blog: { eyebrow: 'Blog', title: 'Wissen für digitale Entscheidungen.', intro: 'Einblicke in Softwareentwicklung, Automatisierung und den Aufbau nachhaltiger digitaler Produkte.', sections: [['Individuelle Software', 'Wann Standardsoftware ausreicht – und wann eine maßgeschneiderte Lösung den entscheidenden Unterschied macht.', ['Software-Strategie', 'Business Prozesse', 'Digitale Produkte']], ['Automatisierung', 'Wie Schnittstellen und gut strukturierte Daten wiederkehrende Arbeit spürbar reduzieren.', ['Workflows', 'Integrationen', 'Künstliche Intelligenz']]] },
  kontakt: { eyebrow: 'Kontakt', title: 'Lassen Sie uns über Ihr Projekt sprechen.', intro: 'Beschreiben Sie uns kurz Ihre Idee oder Herausforderung. Wir melden uns mit einer ersten Einschätzung.', sections: [['Direkt erreichbar', 'AutomatonSoft GmbH\nAm Flugplatz 28\n88483 Burgrieden', ['info@automatonsoft.de', '+49 7392 9378410']], ['Ihr nächster Schritt', 'Ein erstes Gespräch ist unverbindlich und hilft dabei, Anforderungen, Prioritäten und mögliche Vorgehensweisen zu klären.', ['Projekt anfragen', 'Erstgespräch vereinbaren']]] },
  impressum: { eyebrow: 'Rechtliches', title: 'Impressum', intro: 'Angaben gemäß § 5 TMG.', sections: [['Anbieter', 'AutomatonSoft GmbH\nAm Flugplatz 28\n88483 Burgrieden', ['Telefon: +49 7392 9378410', 'E-Mail: info@automatonsoft.de']], ['Hinweise', 'Inhalte dieser Website werden mit Sorgfalt erstellt. Für externe Inhalte, auf die wir verlinken, übernehmen wir keine Haftung.', ['Urheberrecht', 'Haftung für Links']]] },
  datenschutz: { eyebrow: 'Rechtliches', title: 'Datenschutzerklärung', intro: 'Der Schutz Ihrer persönlichen Daten ist uns wichtig.', sections: [['Verantwortliche Stelle', 'AutomatonSoft GmbH\nAm Flugplatz 28\n88483 Burgrieden\nE-Mail: info@automatonsoft.de', ['Kontaktaufnahme', 'Server-Logdaten']], ['Ihre Rechte', 'Sie haben das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch.', ['Auskunft', 'Berichtigung', 'Löschung']]] },
};

export default function MarketingPage({ slug }) {
  const page = content[slug];
  if (!page) return null;
  return <><SiteHeader /><main><section className="page-hero"><div className="hex-pattern" /><div className="container"><div className="breadcrumb"><a href="/">Start</a> / {page.eyebrow}</div><h1>{page.title}</h1><p>{page.intro}</p></div></section><section className="section-pad"><div className="container">{page.sections.map(([title, text, items]) => <section className="section-pad" key={title}><div className="section-head"><div className="eyebrow">{page.eyebrow}</div><h2>{title}</h2><p style={{ whiteSpace: 'pre-line' }}>{text}</p></div><div className="grid grid-3">{items.map((item) => <article className="card" key={item}><h3>{item}</h3></article>)}</div></section>)}<div className="cta-band"><div className="hex-pattern" /><h2>Wie können wir helfen?</h2><p>Wir freuen uns auf Ihre Anfrage.</p><div className="cta-actions"><a href="/kontakt" className="btn btn-primary">Kontakt aufnehmen</a></div></div></div></section></main><SiteFooter /></>;
}
