// Service catalogue shared by the homepage, the services page and the footer.
const services = {
  items: [
    { id: 'custom-software', icon: 'CodeXml', title: 'Custom software', text: 'Business applications built around your processes – not the other way round.', details: 'We analyse your workflows, design a scalable architecture and deliver in transparent milestones – from MVP to enterprise platform.', points: ['Web & backend applications', 'ERP & CRM integrations', 'Legacy modernisation'], more: ['Business process analysis', 'Scalable architecture and APIs', 'Role-based access and audit trails'], reference: { name: 'Hubnity', category: 'workforce-hr-automation' } },
    { id: 'web-mobile', icon: 'Smartphone', title: 'Web & mobile', text: 'Fast, accessible products for customers, partners and field teams.', details: 'Responsive web platforms and native or cross-platform apps on a shared backend, built for performance, security and growth.', points: ['Web platforms & portals', 'iOS & Android apps', 'Progressive web apps'], more: ['Admin dashboards and customer portals', 'Desktop apps for Windows, macOS and Linux', 'Performance and accessibility built in'], reference: { name: 'Hubnity', category: 'workforce-hr-automation' } },
    { id: 'process-automation', icon: 'Workflow', title: 'Process automation', text: 'Remove manual hand-offs between systems, teams and documents.', details: 'We connect ERP, shops, marketplaces and internal tools so data flows automatically and your teams focus on work that matters.', points: ['Workflow automation', 'API & data integration', 'Marketplace & order sync'], more: ['Document and data workflows', 'Notifications and scheduled jobs', 'Monitoring of every integration'], reference: { name: 'E-Commerce Automation Suite', category: 'ecommerce-marketplace-automation' } },
    { id: 'ai-solutions', icon: 'Sparkles', title: 'AI solutions', text: 'Applied AI for clearly defined processes with measurable value.', details: 'We start with a concrete use case, validate it with your data and integrate AI into existing systems – with human control where it counts.', points: ['Intelligent document processing', 'AI assistants & agents', 'Data extraction & classification'], more: ['Voice assistants for customer service', 'Integration into existing systems', 'Human review where it matters'], reference: { name: 'Lisa', category: 'ai-business-solutions' } },
    { id: 'ux-ui-design', icon: 'PenTool', title: 'UX/UI design', text: 'Interfaces your users understand from the very first click.', details: 'Research, prototypes and tested design systems make your product easier to use and faster to evolve.', points: ['UX research & prototyping', 'Design systems', 'Accessible interfaces'], more: ['Clickable prototypes', 'Usability reviews', 'Developer-ready specifications'] },
    { id: 'operations-support', icon: 'ServerCog', title: 'Operations & support', text: 'Secure, monitored operations and continuous development after go-live.', details: 'After go-live we keep your software secure, monitored and up to date – and keep developing it together with you.', points: ['Cloud & on-premise deployment', 'Monitoring & updates', 'Continuous development'], more: ['Backups and recovery', 'Security updates', 'Automated release pipelines (CI/CD)'] },
  ],
};

export default services;
