// Service catalogue shared by the homepage, the services page and the footer.
const services = {
  items: [
    { id: 'custom-software', icon: 'CodeXml', title: 'Individuelle Software', text: 'Business-Anwendungen, die sich nach Ihren Prozessen richten – nicht umgekehrt.', details: 'Wir analysieren Ihre Abläufe, entwerfen eine skalierbare Architektur und liefern in transparenten Etappen – vom MVP bis zur Unternehmensplattform.', points: ['Web- & Backend-Anwendungen', 'ERP- & CRM-Integrationen', 'Modernisierung von Altsystemen'], more: ['Analyse der Geschäftsprozesse', 'Skalierbare Architektur und APIs', 'Rollenbasierte Zugriffe und Audit-Trails'], reference: { name: 'Hubnity', category: 'workforce-hr-automation' } },
    { id: 'web-mobile', icon: 'Smartphone', title: 'Web & Mobile', text: 'Schnelle, barrierearme Produkte für Kunden, Partner und Teams im Außendienst.', details: 'Responsive Webplattformen und native oder plattformübergreifende Apps mit gemeinsamem Backend – ausgelegt auf Performance, Sicherheit und Wachstum.', points: ['Webplattformen & Portale', 'iOS- & Android-Apps', 'Progressive Web Apps'], more: ['Admin-Dashboards und Kundenportale', 'Desktop-Apps für Windows, macOS und Linux', 'Performance und Barrierearmut von Anfang an'], reference: { name: 'Hubnity', category: 'workforce-hr-automation' } },
    { id: 'process-automation', icon: 'Workflow', title: 'Prozessautomatisierung', text: 'Manuelle Übergaben zwischen Systemen, Teams und Dokumenten beseitigen.', details: 'Wir verbinden ERP, Shops, Marktplätze und interne Tools, damit Daten automatisch fließen und sich Ihre Teams auf das Wesentliche konzentrieren.', points: ['Workflow-Automatisierung', 'API- & Datenintegration', 'Marktplatz- & Auftragssynchronisation'], more: ['Dokumenten- und Daten-Workflows', 'Benachrichtigungen und zeitgesteuerte Jobs', 'Monitoring jeder Schnittstelle'], reference: { name: 'E-Commerce Automation Suite', category: 'ecommerce-marketplace-automation' } },
    { id: 'ai-solutions', icon: 'Sparkles', title: 'KI-Lösungen', text: 'Angewandte KI für klar definierte Prozesse mit messbarem Nutzen.', details: 'Wir starten mit einem konkreten Anwendungsfall, validieren ihn mit Ihren Daten und integrieren KI in bestehende Systeme – mit menschlicher Kontrolle, wo es darauf ankommt.', points: ['Intelligente Dokumentenverarbeitung', 'KI-Assistenten & Agenten', 'Datenextraktion & Klassifizierung'], more: ['Sprachassistenten für den Kundenservice', 'Integration in bestehende Systeme', 'Menschliche Prüfung, wo es darauf ankommt'], reference: { name: 'Lisa', category: 'ai-business-solutions' } },
    { id: 'ux-ui-design', icon: 'PenTool', title: 'UX/UI Design', text: 'Oberflächen, die Ihre Anwender vom ersten Klick an verstehen.', details: 'Nutzerforschung, Prototypen und getestete Design-Systeme machen Ihr Produkt einfacher bedienbar und schneller weiterentwickelbar.', points: ['UX-Analyse & Prototyping', 'Design-Systeme', 'Barrierearme Oberflächen'], more: ['Klickbare Prototypen', 'Usability-Reviews', 'Entwicklungsreife Spezifikationen'] },
    { id: 'operations-support', icon: 'ServerCog', title: 'Betrieb & Support', text: 'Sicherer, überwachter Betrieb und kontinuierliche Weiterentwicklung nach dem Go-live.', details: 'Nach dem Go-live halten wir Ihre Software sicher, überwacht und aktuell – und entwickeln sie gemeinsam mit Ihnen weiter.', points: ['Cloud- & On-Premise-Deployment', 'Monitoring & Updates', 'Kontinuierliche Weiterentwicklung'], more: ['Backups und Wiederherstellung', 'Sicherheitsupdates', 'Automatisierte Release-Pipelines (CI/CD)'] },
  ],
};

export default services;
